# Generated by Django 3.2 on 2021-07-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_number', models.TextField(max_length=10)),
                ('designation', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
