# Generated by Django 3.2 on 2021-07-05 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20210705_1356'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='course',
            new_name='course_details',
        ),
    ]
