# Generated by Django 3.2 on 2021-07-05 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_rename_course_details_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=500)),
                ('company_type', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=1000)),
                ('interns_required', models.CharField(max_length=500)),
                ('service', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.add_course')),
            ],
        ),
    ]
