# Generated by Django 3.2 on 2021-07-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_fee',
            field=models.CharField(max_length=1000),
        ),
    ]
