# Generated by Django 3.2 on 2021-07-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_company_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email_address',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='company_registration',
            name='company_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='company_registration',
            name='owner_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
