# Generated by Django 3.2 on 2021-07-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20210709_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='internshipform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100, unique=True)),
                ('lname', models.CharField(max_length=100, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=1000)),
                ('graduation', models.CharField(max_length=1000)),
                ('highersecondary', models.CharField(max_length=1000)),
                ('seconadry', models.CharField(max_length=1000)),
                ('skill', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=1000)),
                ('link2', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=1000)),
                ('internship', models.CharField(max_length=1000)),
                ('tranning', models.CharField(max_length=1000)),
                ('details', models.CharField(max_length=1000)),
                ('field', models.CharField(max_length=1000)),
                ('myfile', models.FileField(upload_to='')),
            ],
        ),
    ]
