# Generated by Django 3.2 on 2021-07-12 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_internshipform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internshipform',
            old_name='seconadry',
            new_name='secondary',
        ),
    ]
