# Generated by Django 3.2 on 2021-07-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_rename_seconadry_internshipform_secondary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipform',
            name='myfile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
