# Generated by Django 3.2 on 2021-07-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_alter_internshipform_myfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=1000)),
                ('blog_subtitle', models.CharField(max_length=1000)),
                ('blog_description', models.TextField(max_length=100000)),
                ('image', models.ImageField(max_length=1000, upload_to='pictures/')),
            ],
        ),
    ]
